name: AdvancedVanish
description: hi
author: quantiom
version: 1.2.8
main: me.quantiom.advancedvanish.AdvancedVanishPlugin
softdepend: [LuckPerms, PlaceholderAPI, GroupManager, PermissionsEx, DiscordSRV, Dynmap, squaremap, LibsDisguises, PlayerParticles, Essentials, PlaceholderAPI, ProtocolLib]
api-version: 1.21
commands:
  vanish:
    description: The main vanish command.
    aliases: [v, advancedvanish]
    usage: /vanish