name: AdvancedVanish
version: 1.8
description: A plugin that allows players to vanish.
author: quantiom
main: me.quantiom.advancedvanish.Main
softdepend:
  - LuckPerms
  - PlaceholderAPI
  - GroupManager
  - PermissionsEx
  - bPermissions
  - DiscordSRV
  - Dynmap
  - squaremap
  - LibsDisguises
  - PlayerParticles
  - Essentials
  - ProtocolLib
api-version: 1.13
commands:
  vanish:
    description: "The main vanish command."
    aliases:
      - v
      - advancedvanish
    usage: "/vanish"
